# Etapa 1: Build da aplicação React
FROM node:18-alpine AS build
WORKDIR /app

COPY ./front/ ./
RUN npm install
RUN npm run build

# Etapa 2: Servindo com Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
