version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - bot

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - TOKEN=${TOKEN}
    env_file:
      - .env
