# Usar uma imagem base do Golang
FROM golang:1.20-alpine

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos do bot para o contêiner
COPY ./bot /app

# Instalar as dependências e compilar a aplicação
RUN go mod tidy
RUN go build -o bot

COPY .env /app/.env

# Comando para rodar o bot
CMD ["./bot"]
